AWSTemplateFormatVersion: "2010-09-09"
Description: "DO NOT DELETE - Deploy a github OIDC provider"
# StackName: github-oidc-povider

Parameters:
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String

Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e

Outputs:
  OIDC:
    Condition: CreateOIDCProvider
    Value: !Ref GithubOidc
    Description: "Github OIDC ARN. For Github actions automation."
    Export:
      Name: github-actions-oidc-arn
